In [1]:
import os
import pandas as pd
import googlemaps

In [2]:
path= os.path.join("..","data","raw","Primary Health Care Centers in Lagos State.xlsx")
df= pd.read_excel(path)
df.head()

,S/N,LGA/LCDA,WARD,NAME OF PHC,ADDRESS
0,1.0,ALIMOSHO LGA,ALABATA,AKOWONJO PHC,"100 AKOWONJO ROAD,VULGANIDER B/S"
1,2.0,NaN,OGUNTADE BAMEKE,ORISUNBARE PHC,"20,EJIGBO ROAD,ORISUNMIBARE, SHASHA"
2,3.0,AGBADO OKE ODO LCDA,AGBADO OKEODO,OKE ODO PHC,"EKORO OKEODO ROAD, OKEODO ABULE EGBA"
3,4.0,NaN,AJASA/AMIKANLE,SURULERE PHC.,"3, FAITH RESCUE BY COMMAND SECONDARY SCHOOL"
4,5.0,NaN,NaN,AMIKANLE PHC,"2/5, FADIPE STR, AGBADO"

In [12]:

df["LGA/LCDA"] = df["LGA/LCDA"].ffill()
df["WARD"] = df["WARD"].ffill()
df.head()

,S/N,LGA/LCDA,WARD,NAME OF PHC,ADDRESS
0,1.0,ALIMOSHO LGA,ALABATA,AKOWONJO PHC,"100 AKOWONJO ROAD,VULGANIDER B/S"
1,2.0,ALIMOSHO LGA,OGUNTADE BAMEKE,ORISUNBARE PHC,"20,EJIGBO ROAD,ORISUNMIBARE, SHASHA"
2,3.0,AGBADO OKE ODO LCDA,AGBADO OKEODO,OKE ODO PHC,"EKORO OKEODO ROAD, OKEODO ABULE EGBA"
3,4.0,AGBADO OKE ODO LCDA,AJASA/AMIKANLE,SURULERE PHC.,"3, FAITH RESCUE BY COMMAND SECONDARY SCHOOL"
4,5.0,AGBADO OKE ODO LCDA,AJASA/AMIKANLE,AMIKANLE PHC,"2/5, FADIPE STR, AGBADO"

from dotenv import load_dotenv
load_dotenv()
gmaps_key=googlemaps.Client(key=os.getenv("GOOGLE_API_KEY"))
df['lat']=None
df['lon']=None

for i in range(len(df)):
    geocode_result=gmaps_key.geocode(df.loc[i,'ADDRESS'])
    try:
        lat=geocode_result[0]["geometry"]["location"]["lat"]
        lng=geocode_result[0]["geometry"]["location"]["lng"]
        df.loc[i,'Lat']=lat
        df.loc[i,'Lon']=lng
    except:
        lat=None
        lng=None
print(df)



output_path = os.path.join(
    "..","data",
    "processed",
    "hospitals_geocoded.csv"
)

df.to_csv(output_path, index=False)

pth=os.path.join("..","data",
    "processed",
    "hospitals_geocoded.csv")
df2=pd.read_csv(pth)
df2.head()

In [4]:
df2 = df2.drop(columns=["lat", "lon"])
df2.head()

,S/N,LGA/LCDA,WARD,NAME OF PHC,ADDRESS,Lat,Lon
0,1.0,ALIMOSHO LGA,ALABATA,AKOWONJO PHC,"100 AKOWONJO ROAD,VULGANIDER B/S",6.599964,3.299789
1,2.0,NaN,OGUNTADE BAMEKE,ORISUNBARE PHC,"20,EJIGBO ROAD,ORISUNMIBARE, SHASHA",6.545638,3.309041
2,3.0,AGBADO OKE ODO LCDA,AGBADO OKEODO,OKE ODO PHC,"EKORO OKEODO ROAD, OKEODO ABULE EGBA",6.643795,3.289045
3,4.0,NaN,AJASA/AMIKANLE,SURULERE PHC.,"3, FAITH RESCUE BY COMMAND SECONDARY SCHOOL",NaN,NaN
4,5.0,NaN,NaN,AMIKANLE PHC,"2/5, FADIPE STR, AGBADO",6.671790,3.278074

In [6]:

df2["LGA/LCDA"] = df2["LGA/LCDA"].ffill()
df2["WARD"] = df2["WARD"].ffill()
df2.head()

,S/N,LGA/LCDA,WARD,NAME OF PHC,ADDRESS,Lat,Lon
0,1.0,ALIMOSHO LGA,ALABATA,AKOWONJO PHC,"100 AKOWONJO ROAD,VULGANIDER B/S",6.599964,3.299789
1,2.0,ALIMOSHO LGA,OGUNTADE BAMEKE,ORISUNBARE PHC,"20,EJIGBO ROAD,ORISUNMIBARE, SHASHA",6.545638,3.309041
2,3.0,AGBADO OKE ODO LCDA,AGBADO OKEODO,OKE ODO PHC,"EKORO OKEODO ROAD, OKEODO ABULE EGBA",6.643795,3.289045
3,4.0,AGBADO OKE ODO LCDA,AJASA/AMIKANLE,SURULERE PHC.,"3, FAITH RESCUE BY COMMAND SECONDARY SCHOOL",NaN,NaN
4,5.0,AGBADO OKE ODO LCDA,AJASA/AMIKANLE,AMIKANLE PHC,"2/5, FADIPE STR, AGBADO",6.671790,3.278074

In [8]:
failed = df2[df2["Lat"].isnull()].copy()
print(len(failed))

62

In [9]:
failed[["LGA/LCDA", "WARD", "NAME OF PHC", "ADDRESS"]]

,LGA/LCDA,WARD,NAME OF PHC,ADDRESS
3,AGBADO OKE ODO LCDA,AJASA/AMIKANLE,SURULERE PHC.,"3, FAITH RESCUE BY COMMAND SECONDARY SCHOOL"
5,AGBADO OKE ODO LCDA,AJASA/AMIKANLE,IKOLA PHC,IKOLA STREET
9,AGBADO OKE ODO LCDA,ABORU,OGUNDIMU PHC,"22 AWOTEDU STR, ABORU"
16,AYOBO IPAJA LCDA,BARUWA,BARUWA PHC,"PROGRESSIVE ESTATE, AJELANWA COMMUNITY, BARUWA"
36,MOSAN OKUNOLA LCDA,MOSAN AKINOGUN,AKINOGUN PHC,PAKO BUS-STOP ADJACENT LIBRARY
...,...,...,...,...
310,IKEJA LGA,SERIKI ARO,ADENIYI JONES PHC,"2 KUDETI, STR, AKORA ESTATE, ABA JOHNSON BUS S..."
327,OJODU LCDA,AKIODE,AKIODE PHC,"5, BAKARE CLOSE, AKIODE, AGINDIGBI"
331,OJODU LCDA,AGUDA,AGUDA PHC,"7,TUNDE GARBY ST, AGUDA TOWN HALL (GROUND FLOOR),"
349,OSHODI ISOLO LGA,MAFOLUKU,AYO NI PHC,"OSHOBOWON STREET, OFF ALHAJI BELLO, BEHIND MAK..."
355,ISOLO LCDA,OKOTA,OKOTA PHC,"14, AYANWUN STREET, FREEDOM ESTATE OKOTA"

In [30]:
#Checking if there are any  missing info
failed["ADDRESS"].isnull().sum()

np.int64(0)

In [10]:
#Checking
(failed["ADDRESS"].str.strip() == "").sum()

np.int64(0)

In [11]:
#Checking to see duplicate 
failed["ADDRESS"].duplicated().sum()

np.int64(2)

In [33]:
failed[failed["ADDRESS"].duplicated(keep=False)][["NAME OF PHC", "ADDRESS"]]

      NAME OF PHC                              ADDRESS
44   KIRIKIRI PHC  INFRONT OF FEMALE PRISONS, KIRIKIRI
45      IREDE HP.             IREDE RIVERINE COMMUNITY
304  KIRIKIRI PHC  INFRONT OF FEMALE PRISONS, KIRIKIRI
305     IREDE HP.             IREDE RIVERINE COMMUNITY

In [34]:
failed[["NAME OF PHC", "ADDRESS"]].head(20)

             NAME OF PHC                                            ADDRESS
3          SURULERE PHC.        3, FAITH RESCUE BY COMMAND SECONDARY SCHOOL
5              IKOLA PHC                                       IKOLA STREET
9           OGUNDIMU PHC                              22 AWOTEDU STR, ABORU
16            BARUWA PHC     PROGRESSIVE ESTATE, AJELANWA COMMUNITY, BARUWA
36          AKINOGUN PHC                     PAKO BUS-STOP ADJACENT LIBRARY
44          KIRIKIRI PHC                INFRONT OF FEMALE PRISONS, KIRIKIRI
45             IREDE HP.                           IREDE RIVERINE COMMUNITY
70         EWU ELEPE PHC                                 ELEPE B/STOP,ELEPE
82          LOSI OBA PHC                             ISELE B/STOP,ITA OLIWO
87            PARAFA PHC                                     PARAFA VILLAGE
102             IDERA HP                                      IDERA VILLAGE
103           AGBOYI PHC                                    AGBOYI RIVERINE
114           WRIGHT PHC      EMMANUEL STREET (INSIDE WRIGHT PRIMARY SCHOOL
115                  NaN                              COMPOUND, PALMGROOVE)
125          SAGIDAN PHC                          16, AGBORIODE ST, SAGIDAN
134  ADO IKOSI BEACH PHC                       ALONG ADO / AGBOWA ROAD, ADO
147           OTUNLA PHC                                        OTUNLA TOWN
150           DEBOJO PHC                                   OKUN-DEBOJO TOWN
153         OKUN ISE PHC  FROM FOLU BUS-STOP, BRANCH TO ISE, 2 MILES FRO...
154                  NaN                                           TOWNSHIP

In [14]:
df2.loc[110:116, ["NAME OF PHC", "ADDRESS"]]

                  NAME OF PHC                                        ADDRESS
110           EVA ADELAJA PHC          ADJACENT EVA ADELAJA SECONDARY SCHOOL
111                 AKOKA PHC                    33,IBUNKUN-OLU STREET AKOKA
112             BAJULAIYE PHC                    11, HUMANI STREET BAJULAIYE
113               OHEKENU PHC                      15, OHEKENU STREET FADEYI
114                WRIGHT PHC  EMMANUEL STREET (INSIDE WRIGHT PRIMARY SCHOOL
115                       NaN                          COMPOUND, PALMGROOVE)
116  DR IBIJOKE SANWO-OLU PHC          OLUWADAREST, OFF BAJULAIYE RD, SOMOLU

In [15]:
df2.loc[150:155, ["LGA/LCDA", "WARD", "NAME OF PHC", "ADDRESS"]]

,LGA/LCDA,WARD,NAME OF PHC,ADDRESS
150,IBEJU/LEKKI LGA,ORIMEDU III,DEBOJO PHC,OKUN-DEBOJO TOWN
151,IBEJU/LEKKI LGA,ORIMEDU II,IBEREKODO PHC,BESIDE RCM PRY.SCH.IBEREKODO
152,IBEJU/LEKKI LGA,ORIMEDU I,ORIMEDU PHC,ORIMEDU COMMUNITY TOWN
153,LEKKI LCDA,ISE IGBOGUN,OKUN ISE PHC,"FROM FOLU BUS-STOP, BRANCH TO ISE, 2 MILES FRO..."
154,LEKKI LCDA,ISE IGBOGUN,NaN,TOWNSHIP
155,LEKKI LCDA,ISE IGBOGUN,ISE PHC,"OKUN ISE, LEKKI"

In [38]:
failed[failed["ADDRESS"].duplicated(keep=False)][
    ["NAME OF PHC", "ADDRESS"]
]

      NAME OF PHC                              ADDRESS
44   KIRIKIRI PHC  INFRONT OF FEMALE PRISONS, KIRIKIRI
45      IREDE HP.             IREDE RIVERINE COMMUNITY
304  KIRIKIRI PHC  INFRONT OF FEMALE PRISONS, KIRIKIRI
305     IREDE HP.             IREDE RIVERINE COMMUNITY